refactor(build, ci): Generic ESK changes
- Switch to Generic ESK source
- Drop LXC support
- Add raw, lz4 boot image build support

Signed-off-by: bachnxuan <bachnxuan@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,19 +12,12 @@ jobs:
       matrix:
         variant:
           - { name: "Non-KSU", KSU: "NONE", SUSFS: "false", LXC: "false" }
-          - { name: "Non-KSU-LXC", KSU: "NONE", SUSFS: "false", LXC: "true" }
           - { name: "KSU", KSU: "OFFICIAL", SUSFS: "false", LXC: "false" }
           - { name: "KSU-SUSFS", KSU: "OFFICIAL", SUSFS: "true", LXC: "false" }
-          - { name: "KSU-LXC", KSU: "OFFICIAL", SUSFS: "false", LXC: "true" }
-          - { name: "KSU-SUSFS-LXC", KSU: "OFFICIAL", SUSFS: "true", LXC: "true" }
           - { name: "KSUN", KSU: "NEXT", SUSFS: "false", LXC: "false" }
           - { name: "KSUN-SUSFS", KSU: "NEXT", SUSFS: "true", LXC: "false" }
-          - { name: "KSUN-LXC", KSU: "NEXT", SUSFS: "false", LXC: "true" }
-          - { name: "KSUN-SUSFS-LXC", KSU: "NEXT", SUSFS: "true", LXC: "true" }
           - { name: "SUKISU", KSU: "SUKI", SUSFS: "false", LXC: "false" }
           - { name: "SUKISU-SUSFS", KSU: "SUKI", SUSFS: "true", LXC: "false" }
-          - { name: "SUKISU-LXC", KSU: "SUKI", SUSFS: "false", LXC: "true" }
-          - { name: "SUKISU-SUSFS-LXC", KSU: "SUKI", SUSFS: "true",LXC: "true" }
     name: Build ${{ matrix.variant.name }} variant
     uses: ./.github/workflows/build.yml
     secrets: inherit
@@ -123,7 +116,6 @@ jobs:
             | **-NEXT** | KernelSU Next |
             | **-NONE** | No KernelSU |
             | **-SUSFS** | SUSFS Support |
-            | **-LXC** | LXC Support |
 
             > [!IMPORTANT]
             > For installation instructions and issue reporting guidelines, please refer to the README.md
@@ -156,7 +148,7 @@ jobs:
 
             if ! echo "$resp" | jq -e '.ok == true' > /dev/null; then
                 err=$(echo "$resp" | jq -r '.description')
-                echo "::error::telegram_send_msg(): failed to send message: ${err:-Unknown error} $*" >&2
+                echo "::error::telegram_send_msg(): ${err:-Unknown error} $*" >&2
                 exit 1
             fi
           }
